<?php
    $month = date("m");
    if($month==1)
    {
        echo"January";
    }
    
    elseif($month==2)
    {
        echo"February";
    }
    elseif($month==3)
    {
        echo"March";
    }
    elseif($month==4)
    {
        echo"April";
    }
    elseif($month==5)
    {
        echo"May";
    }
    elseif($month==06)
    {
        echo"June";
    }
    elseif($month==7)
    {
        echo"July";
    }
    elseif($month==8)
    {
        echo"August";
    }
    elseif($month==9)
    {
        echo"September";
    }
    elseif($month==10)
    {
        echo"October";
    }
    elseif($month==11)
    {
        echo"November";
    }
    else{
        echo"December";
    }
?>